// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PurchasingSystem.Models;

public partial class Part
{
    public int PartId { get; set; }

    public string Description { get; set; }

    public decimal PurchasePrice { get; set; }

    public decimal SellingPrice { get; set; }

    public int QuantityOnHand { get; set; }

    public int ReorderLevel { get; set; }

    public int QuantityOnOrder { get; set; }

    public int CategoryId { get; set; }

    public string Refundable { get; set; }

    public bool Discontinued { get; set; }

    public int VendorId { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; } = new List<PurchaseOrderDetail>();

    public virtual Vendor Vendor { get; set; }
}