// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PurchasingSystem.Models;

public partial class PurchaseOrderDetail
{
    public int PurchaseOrderDetailId { get; set; }

    public int PurchaseOrderId { get; set; }

    public int PartId { get; set; }

    public int Quantity { get; set; }

    public decimal PurchasePrice { get; set; }

    public string VendorPartNumber { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    public virtual Part Part { get; set; }

    public virtual PurchaseOrder PurchaseOrder { get; set; }
}