// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PurchasingSystem.Models;

public partial class UnorderedPurchaseItemCart
{
    public int UnorderedItemId { get; set; }

    public int ReceiveOrderId { get; set; }

    public string Description { get; set; }

    public string VendorPartNumber { get; set; }

    public int Quantity { get; set; }

    public bool RemoveFromViewFlag { get; set; }
}